kind: Service
apiVersion: v1
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
  spec:
    ports:
    - name: postgres
      port: 5432
      nodePort: 30432
    type: NodePort
    selector:
      app: postgres
