kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    app: postgres
  spec:
    ports:
     - port: 80
       nodePort: 30200
    type: NodePort
    selector:
      app: pgadmin

